name: Daily Weather

on:
  schedule:
    - cron: "5 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  append-raw:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Init JSON
        run: |
          [ -f weather.json ] || echo '[]' > weather.json

      - name: Fetch Weather Data
        env:
          KEY: ${{ secrets.OPEN_WEATHER_MAP_KEY }}
        run: |
          old=$(cat weather.json)
          new=$(curl -s "https://api.openweathermap.org/data/2.5/weather?q=Amoy&appid=${KEY}&units=metric")
          jq --argjson n "$new" '. + [$n]' <<< "$old" > tmp.json
          mv tmp.json weather.json

      - name: Commit & push
        run: |
          git config --local user.name  "DoubledConG"
          git config --local user.email "992196871@qq.com"
          git add weather.json
          if ! git diff --cached --quiet; then
            git commit -m "feat: ğŸŒ¤ Update Weather $(date -I)"
            git push
          else
            echo "æ— å˜åŒ–ï¼Œè·³è¿‡æäº¤"
          fi
